### ISSUE TITLE
Images are not receiving from s3 bucket

### ISSUE THREAD

**Issue by bipashant** [sharetribe/sharetribe#1568]
Hi
I've a fresh copy of sharetribe on my ec2 production server.Everything is working fine but while using s3 credentials for uploading images.
I followed the instruction as mentioned here https://github.com/sharetribe/sharetribe/issues/665 .
While creating a listing images are get uploaded in the s3 but while displaying thumbnail I'm getting following error.

``` ruby
<Error>
    <Code>NoSuchKey</Code>
   <Message>The specified key does not exist.</Message>
   <Key>
images/listing_images/images/13/thumb/12301710_10208539414865556_5793515947438563164_n.jpg
  </Key>
  <RequestId>691C95345Y323365C40BB3</RequestId>
  <HostId>
 /asdasdkadnfkansjhafjka/bW8=
  </HostId>
</Error>
```

I've added in my config.yml file

```
  # Default bucket
  s3_bucket_name: ************

  # Bucket for files users upload directly to S3. You can add an expiration policy to these files.
  s3_upload_bucket_name:

  # AWS keys
  aws_access_key_id: *************
  aws_secret_access_key: **********

```

I've no idea about `s3_upload_bucket_name`. Is there anything I need to setup to fix the issue.

Any appreciation will be appreciated. Thank you
