### ISSUE TITLE
Emails aren't getting sent/received via Amazon SES for a self-hosted app

### ISSUE THREAD

**Issue by GildedHonour** [sharetribe/sharetribe#3358]
I'm running my app at Amazon EC2, staging mode, and using Amazon SES. My config:
```


    staging:
      domain: "staging.my_domain123.com"

      # AWS keys
      aws_access_key_id: [.....]
      aws_secret_access_key: [.....]

      mail_delivery_method: smtp
      smtp_email_domain: my_domain123.com
      smtp_email_address: email-smtp.us-west-2.amazonaws.com 
      smtp_email_user_name: aabbcc 
      smtp_email_password: ddeejj 
      smtp_email_port: 587 

      aws_ses_region: "us-west-2"
      sharetribe_mail_from_address: "abcd@my_domain123.com"
      sns_notification_token: "arn:aws:sns:us-west-2:aabbccdd:abdcde"

```

No matter what I try, I won't receive an email after I sign up. It seems they aren't even getting sent. 

 **I don't see anything in "/var/log/staging.my_domain123.com.log related to email either.**

What could be the cause? 

Anything to do with the port 587 being open/closed in my security group?
